name: C++ Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-test:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build tests
              run: |
                  if (-not (Test-Path build)) { New-Item -ItemType Directory -Path build -Force | Out-Null }
                  g++ -std=c++17 -I. src/Executor/executor.cpp src/Lexer/Lexer.cpp src/Parser/Parser.cpp src/Interpreter/Interpreter.cpp src/Scope/Scope.cpp src/Utility/utility.cpp tests/src/runTests.cpp -o build/run_tests.exe
              shell: pwsh

            - name: Run tests
              run: ./build/run_tests.exe
